
name: Nimble Speed Test
on:
  workflow_dispatch:
jobs:
  build:
    if: false  # Disabled
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v2

      - name: Test Speed
        run: nimble install fidget2

      - name: List Installed Nim packages
        run: nimble list -i --ver
