name: Test Install From a .nimble File
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v6

      - name: Compile Nimby
        run: nim c -d:release -d:monkey src/nimby.nim

      - name: Boxy
        run: git clone --depth 1 https://github.com/treeform/boxy.git

      - name: Install Boxy nimble file
        run: src/nimby install boxy/boxy.nimble

      - name: List Installed Packages
        run: src/nimby list

      - name: List Dependency Tree
        run: src/nimby tree

      - name: Build Boxy
        run: nim c -d:release boxy/src/boxy.nim
