
name: Nimby Use Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Nimby
        run: curl -L -o nimby https://github.com/treeform/nimby/releases/download/v0.1.2/nimby-Linux-X64

      - name: Set executable permissions for Nimby
        run: chmod +x nimby

      - name: Use Nim 2.2.6
        run: ./nimby use 2.2.6

      - name: Install Fidget2
        run: ./nimby install fidget2

      - name: List Installed Nim packages
        run: ./nimby list

      - name: List Dependencies in Tree View
        run: ./nimby tree fidget2

      - name: Test Fidget2 Compilation
        run: |
          cd fidget2
          nim c -r src/fidget2.nim
