name: Test Sync Lock File
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    if: false  # Disabled
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v3

      - name: Compile Nimby
        run: nim c -d:release -d:monkey src/nimby.nim

      - name: Sync Test Lock File
        run: src/nimby sync tests/nimby.lock

      - name: List Installed Packages
        run: src/nimby list

      - name: List Dependency Tree
        run: src/nimby tree
