name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_34_x86_64
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Install build dependencies (Linux container)
        if: matrix.container
        run: yum install -y git gcc make which tar gzip curl

      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v6

      - name: Build Nimby
        run: nim c -d:release -d:monkey src/nimby.nim

      - name: Add Nimby to PATH
        run: echo "$PWD/src" >> "$GITHUB_PATH"

      - name: Run Nimby Tests
        run: nim r tests/test_parsing.nim
