name: Test Sync Lock File
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            container: quay.io/pypa/manylinux_2_34_x86_64
          - os: ubuntu-22.04-arm
            container: quay.io/pypa/manylinux_2_34_aarch64
          - os: macos-latest
            container: null
          - os: windows-latest
            container: null
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - name: Install build dependencies (Linux container)
        if: matrix.container
        run: yum install -y git gcc make which tar gzip curl

      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v6

      - name: Compile Nimby
        run: nim c -d:release -d:monkey src/nimby.nim

      - name: Sync Test Lock File
        run: src/nimby sync tests/nimby.lock

      - name: List Installed Packages
        run: src/nimby list

      - name: List Dependency Tree
        run: src/nimby tree
