
name: Test install Nim
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: treeform/setup-nim-action@v2

      - name: Compile Nimby
        run: nim c --mm:atomicArc -d:release src/nimby.nim

      - name: Install Nim Compiler
        run: src/nimby use -V 2.2.6

      - name: Print Nimby Folder
        run: ls "$HOME/.nimby"

      - name: Print Nimby nim folder
        run: ls "$HOME/.nimby/nim"

      - name: Print Nimby nim/bin folder
        run: ls "$HOME/.nimby/nim/bin"

      # - name: Set Nim to be executable
      #   run: chmod +x "$HOME/.nimby/nim/bin/nim"

      - name: Add Nim to PATH
        run: echo "$HOME/.nimby/nim/bin" >> "$GITHUB_PATH"

      - name: Print PATH
        run: echo "$PATH"

      - name: Print Nim version (Full Path)
        run: $HOME/.nimby/nim/bin/nim --version

      - name: Print Nim version (Normal)
        run: nim --version
